packages:
<<<<<<< HEAD
  - 'services/*'
  - 'shared/*'
=======
  - services/*
  - shared/*
onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - esbuild
  - prisma
>>>>>>> 80848195b954cd48b7cf34d46db2de99581cbe03
